import { strict as assert } from "node:assert";
import { isExpectedActivePrice, isExpectedPaidCheckout, isExpectedStoredCheckout } from "../api/_lib/commerce";
import { checkoutRequest } from "../api/_lib/checkout";
import { isAccessToken } from "../api/_lib/access-token";
import { legalConfigurationIsComplete, salesReleaseConfigurationComplete } from "../api/_lib/env";
import { FEEDBACK_COMMENT_MAX_LENGTH, feedbackPayload } from "../api/_lib/feedback";
import { accessTokenHash, matchesAccessTokenHash } from "../api/_lib/token";
import { PUBLIC_SALES_CONFIG } from "../src/public-sales-config";

process.env.STRIPE_LAUNCH_PRICE_ID = "price_launch_980";
process.env.STRIPE_SALE_PRICE_MODE = "launch";
const launchPrice = { id: "price_launch_980", type: "one_time" as const, currency: "jpy", unit_amount: 980 };
assert.equal(isExpectedActivePrice(launchPrice), true, "the launch Price is the only valid Checkout Price");
assert.equal(isExpectedActivePrice({ ...launchPrice, id: "price_regular_1980" }), false, "the regular Price cannot be used during the launch offer");
assert.equal(isExpectedActivePrice({ ...launchPrice, unit_amount: 1980 }), false, "a mismatched amount cannot start Checkout");
assert.equal(isExpectedPaidCheckout({ payment_status: "paid", currency: "jpy", amount_total: 980 }, ["price_launch_980"]), true, "a paid JPY 980 launch checkout is accepted");
assert.equal(isExpectedPaidCheckout({ payment_status: "paid", currency: "jpy", amount_total: 1980 }, ["price_launch_980"]), false, "a mismatched checkout amount is rejected");
assert.equal(isExpectedPaidCheckout({ payment_status: "paid", currency: "jpy", amount_total: 980 }, ["price_regular_1980"]), false, "a regular Price checkout is rejected during launch");
assert.equal(isExpectedPaidCheckout({ payment_status: "unpaid", currency: "jpy", amount_total: 980 }, ["price_launch_980"]), false, "unpaid checkout sessions are rejected");
process.env.STRIPE_SALE_PRICE_MODE = "regular";
process.env.STRIPE_REGULAR_PRICE_ID = "price_regular_1980";
assert.equal(isExpectedActivePrice({ id: "price_regular_1980", type: "one_time", currency: "jpy", unit_amount: 1980 }), true, "the active regular Price is valid after the campaign mode changes");
process.env.STRIPE_SALE_PRICE_MODE = "launch";
const id = "f8c1e8c5-8fa8-4cf9-9ca4-d4a8cd14a8c8";
const token = "A".repeat(43);
assert.deepEqual(checkoutRequest({ resultId: id, accessToken: token, amount: 1, currency: "usd", priceId: "price_attacker" }), { resultId: id, accessToken: token }, "Checkout input accepts only result proof and ignores client-provided price fields");
assert.equal(checkoutRequest({ resultId: id, amount: 980 }), undefined, "Checkout cannot be started without access-token proof");
assert.equal(isAccessToken("A".repeat(43)), true, "an opaque 32-byte base64url token is accepted");
assert.equal(isAccessToken("bad-token"), false, "an invalid access token cannot query a paid report");
process.env.REPORT_ACCESS_TOKEN_SECRET = "test-only-secret-at-least-32-bytes";
assert.equal(matchesAccessTokenHash(token, accessTokenHash(token)), true, "access-token proof uses a timing-safe HMAC comparison");
assert.equal(matchesAccessTokenHash("B".repeat(43), accessTokenHash(token)), false, "invalid access-token proof stays closed");
assert.equal(isExpectedStoredCheckout({ payment_status: "paid", currency: "jpy", amount_total: 980 }, ["price_launch_980"], { priceId: "price_launch_980", amount: 980, currency: "jpy" }), true, "Webhook verifies the price snapshot stored when Checkout started");
process.env.STRIPE_SALE_PRICE_MODE = "regular";
assert.equal(isExpectedStoredCheckout({ payment_status: "paid", currency: "jpy", amount_total: 980 }, ["price_launch_980"], { priceId: "price_launch_980", amount: 980, currency: "jpy" }), true, "a later campaign-mode change does not invalidate an in-flight paid Checkout");
process.env.STRIPE_SALE_PRICE_MODE = "launch";
assert.equal(legalConfigurationIsComplete({ LEGAL_SELLER_NAME: "seller", LEGAL_RESPONSIBLE_PERSON: "owner", LEGAL_ADDRESS: "address", LEGAL_PHONE: "phone", LEGAL_CONTACT_EMAIL: PUBLIC_SALES_CONFIG.contactEmail, LEGAL_SUPPORT_HOURS: "hours", LEGAL_EFFECTIVE_DATE: "2026-07-14" }), true, "Checkout may proceed only with all legal display values configured");
assert.equal(legalConfigurationIsComplete({ LEGAL_SELLER_NAME: "seller" }), false, "missing legal configuration blocks Checkout");
const productionEnvironment = { LEGAL_SELLER_NAME: "seller", LEGAL_RESPONSIBLE_PERSON: "owner", LEGAL_ADDRESS: "address", LEGAL_PHONE: "phone", LEGAL_CONTACT_EMAIL: PUBLIC_SALES_CONFIG.contactEmail, LEGAL_SUPPORT_HOURS: "hours", LEGAL_EFFECTIVE_DATE: "2026-07-14", SERVICE_NAME: PUBLIC_SALES_CONFIG.diagnosisName, DIAGNOSIS_NAME: PUBLIC_SALES_CONFIG.diagnosisName, PAID_PRODUCT_NAME: PUBLIC_SALES_CONFIG.paidProductName, MAIN_TYPE_NAMES: "one,two,three,four", SUBTYPE_NAMES: "a,b,c" };
const previousEnvironment = { ...process.env };
Object.assign(process.env, productionEnvironment);
assert.equal(salesReleaseConfigurationComplete(), true, "a production release requires legal and final naming configuration");
delete process.env.PAID_PRODUCT_NAME;
assert.equal(salesReleaseConfigurationComplete(), false, "a draft product name cannot pass the production release check");
Object.keys(process.env).forEach((key) => { if (!(key in previousEnvironment)) delete process.env[key]; });
assert.deepEqual(feedbackPayload({ resultId: id, accessToken: token, rating: 5, comment: "  役に立ちました  " }), { resultId: id, accessToken: token, rating: 5, comment: "役に立ちました" }, "feedback trims comments without persisting its access proof");
assert.deepEqual(feedbackPayload({ resultId: id, accessToken: token, rating: 3, comment: "   " }), { resultId: id, accessToken: token, rating: 3 }, "blank comments are omitted");
assert.equal(feedbackPayload({ resultId: id, accessToken: token, rating: 6 }), undefined, "invalid ratings are rejected");
assert.equal(feedbackPayload({ resultId: id, accessToken: token, rating: 4, comment: "x".repeat(FEEDBACK_COMMENT_MAX_LENGTH + 1) }), undefined, "oversized comments are rejected");
console.log("sales API validation tests passed");
